permalink: /:categories/:year/:month/:title
highlighter: rouge
gems:
  - jekyll-redirect-from
navigation:
  - title: 홈
    url: /
  - title: 다운로드
    url: "https://julialang.org/downloads/"
  - title: 문서
    url: "/ko/latest/"
    class: docs
  - title: 블로그
    url: "https://julialang.org/blog/"
  - title: 커뮤니티
    url: "https://julialang.org/community/"
  - title: 배우기
    url: "https://julialang.org/learning/"
  - title: 연구
    url: "https://julialang.org/research/"
  - title: JSoC
    url: "https://julialang.org/jsoc/"
collections:
  publications:
    permalink: /publications/:path
